In [2]:
import pandas as pd
import numpy as np

In [3]:
data = np.random.randn(4,3)

In [4]:
data

array([[ 0.82470075, -0.73865218, -0.86365295],
       [-1.36070347, -0.08638145,  0.78491186],
       [-0.68606426, -0.27614986, -0.73558205],
       [-0.63861303, -1.28850932,  0.14084117]])

In [5]:
data_frame = pd.DataFrame(data)

In [6]:
data_frame

          0         1         2
0  0.824701 -0.738652 -0.863653
1 -1.360703 -0.086381  0.784912
2 -0.686064 -0.276150 -0.735582
3 -0.638613 -1.288509  0.140841

In [7]:
type(data_frame)

pandas.DataFrame

In [8]:
type(data_frame[0])

pandas.Series

In [9]:
new_df = pd.DataFrame(data,index=["Atil","Zeynep","Atlas","Mehmet"],columns = ["Salary","Age","Seniority"])

In [10]:
new_df

          Salary       Age  Seniority
Atil    0.824701 -0.738652  -0.863653
Zeynep -1.360703 -0.086381   0.784912
Atlas  -0.686064 -0.276150  -0.735582
Mehmet -0.638613 -1.288509   0.140841

In [11]:
new_df["Age"]

Atil     -0.738652
Zeynep   -0.086381
Atlas    -0.276150
Mehmet   -1.288509
Name: Age, dtype: float64

In [12]:
new_df["Salary"]

Atil      0.824701
Zeynep   -1.360703
Atlas    -0.686064
Mehmet   -0.638613
Name: Salary, dtype: float64

In [13]:
new_df[["Salary","Age"]]

          Salary       Age
Atil    0.824701 -0.738652
Zeynep -1.360703 -0.086381
Atlas  -0.686064 -0.276150
Mehmet -0.638613 -1.288509

In [15]:
new_df.loc["Atil"] #eğer row tuple bulmaya çalışıyprsak

Salary       0.824701
Age         -0.738652
Seniority   -0.863653
Name: Atil, dtype: float64

In [16]:
new_df.iloc[0]

Salary       0.824701
Age         -0.738652
Seniority   -0.863653
Name: Atil, dtype: float64

In [17]:

new_df.iloc[1]

Salary      -1.360703
Age         -0.086381
Seniority    0.784912
Name: Zeynep, dtype: float64

In [22]:
#eğer cloumn ları indexlere göre seçmek istiyorsak
new_df.iloc[:,1]

Atil     -0.738652
Zeynep   -0.086381
Atlas    -0.276150
Mehmet   -1.288509
Name: Age, dtype: float64

In [24]:
#data manipulation - veri ekleme çıkarma

In [18]:
new_df

          Salary       Age  Seniority
Atil    0.824701 -0.738652  -0.863653
Zeynep -1.360703 -0.086381   0.784912
Atlas  -0.686064 -0.276150  -0.735582
Mehmet -0.638613 -1.288509   0.140841

In [34]:
new_df["Extra"] = 10

In [35]:
new_df

          Salary       Age  Seniority  Extra
Atil    0.824701 -0.738652  -0.863653     10
Zeynep -1.360703 -0.086381   0.784912     10
Atlas  -0.686064 -0.276150  -0.735582     10
Mehmet -0.638613 -1.288509   0.140841     10

In [36]:
new_df.drop("Extra",axis=1,inplace=True)
#axis boş bırakılırsa yada =0 sa row silinir,
#axis eğer =1 ise column silinir
#inplace de new_df

In [26]:
new_df

          Salary       Age  Seniority
Atil    0.824701 -0.738652  -0.863653
Zeynep -1.360703 -0.086381   0.784912
Atlas  -0.686064 -0.276150  -0.735582
Mehmet -0.638613 -1.288509   0.140841

In [37]:
new_df.loc["Atlas"]

Salary      -0.686064
Age         -0.276150
Seniority   -0.735582
Name: Atlas, dtype: float64

In [38]:
new_df.loc["Atlas"]["Salary"]

np.float64(-0.686064258420172)

In [49]:
new_df.loc["Atlas","Salary"]

np.float64(-0.686064258420172)

In [52]:
new_df.loc["Atlas","Salary"]=100

In [53]:
new_df

            Salary       Age  Seniority
Atil      0.824701 -0.738652  -0.863653
Zeynep   -1.360703 -0.086381   0.784912
Atlas   100.000000 -0.276150  -0.735582
Mehmet   -0.638613 -1.288509   0.140841

In [55]:
boolean_frame = new_df > 0

In [56]:
boolean_frame

        Salary    Age  Seniority
Atil      True  False      False
Zeynep   False  False       True
Atlas     True  False      False
Mehmet   False  False       True

In [57]:
new_df[boolean_frame]

            Salary  Age  Seniority
Atil      0.824701  NaN        NaN
Zeynep         NaN  NaN   0.784912
Atlas   100.000000  NaN        NaN
Mehmet         NaN  NaN   0.140841

In [58]:
new_df[new_df > 0]

            Salary  Age  Seniority
Atil      0.824701  NaN        NaN
Zeynep         NaN  NaN   0.784912
Atlas   100.000000  NaN        NaN
Mehmet         NaN  NaN   0.140841

In [59]:
new_df[new_df["Salary"] > 0.3]

           Salary       Age  Seniority
Atil     0.824701 -0.738652  -0.863653
Atlas  100.000000 -0.276150  -0.735582

In [60]:
new_df[new_df["Age"] > 0.5]

Empty DataFrame
Columns: [Salary, Age, Seniority]
Index: []

In [63]:
#dataFrame indexing

In [64]:
new_df

            Salary       Age  Seniority
Atil      0.824701 -0.738652  -0.863653
Zeynep   -1.360703 -0.086381   0.784912
Atlas   100.000000 -0.276150  -0.735582
Mehmet   -0.638613 -1.288509   0.140841

In [65]:
new_df.reset_index()

    index      Salary       Age  Seniority
0    Atil    0.824701 -0.738652  -0.863653
1  Zeynep   -1.360703 -0.086381   0.784912
2   Atlas  100.000000 -0.276150  -0.735582
3  Mehmet   -0.638613 -1.288509   0.140841

In [67]:
reset_frame = new_df.reset_index()

In [68]:
new_indices = ["Ati", "Zey", "Atl", "Meh"]

In [74]:
new_df["NewIndex"] = new_indices

In [75]:
new_df.set_index("NewIndex", inplace=True)

In [76]:
new_df

           index      Salary       Age  Seniority
NewIndex
Ati         Atil    0.824701 -0.738652  -0.863653
Zey       Zeynep   -1.360703 -0.086381   0.784912
Atl        Atlas  100.000000 -0.276150  -0.735582
Meh       Mehmet   -0.638613 -1.288509   0.140841

In [77]:
new_df.loc["Ati"]

index            Atil
Salary       0.824701
Age         -0.738652
Seniority   -0.863653
Name: Ati, dtype: object

In [78]:
# multi index

In [80]:
first_index = ["Simpson","Simpson","Simpson","South Park", "South Park", "South Park"]

In [81]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [82]:
zipped_index = list(zip(first_index, inner_index))

In [83]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [84]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [85]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [86]:

sample_values = np.ones((6,2))

In [87]:
sample_values

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [88]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Age", "Salary"])

In [89]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [90]:

big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [91]:
big_df.loc["Simpson"]

       Age  Salary
Homer  1.0     1.0
Bart   1.0     1.0
Marge  1.0     1.0

In [92]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64